In [63]:
from fastai.tabular.all import *
import pandas as pd
import pathlib
import numpy as np

In [2]:
clean_df = pd.read_csv('./df_training_ml.csv')
type(clean_df.iloc[0])

pandas.core.series.Series

In [3]:
learner2 = load_learner('../models/model_gs.pt')

In [4]:
learner2.predict(clean_df.iloc[0])

(   home_scorer_1  home_scorer_2  home_scorer_3  home_scorer_4  home_scorer_5  \
 0       1.341905       1.539844      -0.493097      -0.525795      -0.298516   
 
    away_scorer_1  away_scorer_2  away_scorer_3  away_scorer_4  away_scorer_5  \
 0       0.170147       0.909272       1.475447      -0.805403      -0.044956   
 
    ...  home_rebounder_2  home_rebounder_3  home_rebounder_4  \
 0  ...          1.449007           2.18121          1.559764   
 
    home_rebounder_5  away_rebounder_1  away_rebounder_2  away_rebounder_3  \
 0          0.414418          -0.25663         -0.779908          -0.19157   
 
    away_rebounder_4  away_rebounder_5  home_won  
 0          0.535016          1.261637       1.0  
 
 [1 rows x 21 columns],
 tensor(1),
 tensor([0.3181, 0.6819]))

In [5]:
type(clean_df.iloc[0])

pandas.core.series.Series

In [6]:
dict1 = {'home_scorer_1':10., 'home_scorer_2':9., 'home_scorer_3':8.,
       'home_scorer_4':6., 'home_scorer_5':5., 'away_scorer_1':19., 'away_scorer_2':18.,
       'away_scorer_3': 15., 'away_scorer_4':13., 'away_scorer_5':5.,
         'home_rebounder_1': 5.,'home_rebounder_2': 4., 'home_rebounder_3':3, 'home_rebounder_4':2.,
       'home_rebounder_5':0.1, 'away_rebounder_1':5, 'away_rebounder_2':4,
       'away_rebounder_3':3, 'away_rebounder_4':2, 'away_rebounder_5':1}

In [7]:
learner2.predict(pd.Series(dict1))

(   home_scorer_1  home_scorer_2  home_scorer_3  home_scorer_4  home_scorer_5  \
 0      -2.134515      -1.872727      -1.505851      -1.741949      -1.421627   
 
    away_scorer_1  away_scorer_2  away_scorer_3  away_scorer_4  away_scorer_5  \
 0      -0.032814       1.205871       1.346297       1.566919      -1.410483   
 
    ...  home_rebounder_2  home_rebounder_3  home_rebounder_4  \
 0  ...         -1.128209         -1.310471         -2.013694   
 
    home_rebounder_5  away_rebounder_1  away_rebounder_2  away_rebounder_3  \
 0         -4.016935         -1.254631         -1.116598         -1.300052   
 
    away_rebounder_4  away_rebounder_5  home_won  
 0         -1.999187         -2.739885       0.0  
 
 [1 rows x 21 columns],
 tensor(0),
 tensor([0.7805, 0.2195]))

In [8]:
print(learner2.predict(clean_df.iloc[0]))
row, clas, prob = learner2.predict(clean_df.iloc[0])

(   home_scorer_1  home_scorer_2  home_scorer_3  home_scorer_4  home_scorer_5  \
0       1.341905       1.539844      -0.493097      -0.525795      -0.298516   

   away_scorer_1  away_scorer_2  away_scorer_3  away_scorer_4  away_scorer_5  \
0       0.170147       0.909272       1.475447      -0.805403      -0.044956   

   ...  home_rebounder_2  home_rebounder_3  home_rebounder_4  \
0  ...          1.449007           2.18121          1.559764   

   home_rebounder_5  away_rebounder_1  away_rebounder_2  away_rebounder_3  \
0          0.414418          -0.25663         -0.779908          -0.19157   

   away_rebounder_4  away_rebounder_5  home_won  
0          0.535016          1.261637       1.0  

[1 rows x 21 columns], tensor(1), tensor([0.3181, 0.6819]))


In [10]:
clean_df.iloc[0]

home_won             0.000000
home_scorer_1       24.951220
home_scorer_2       19.012195
home_scorer_3       10.500000
home_scorer_4        8.548780
home_scorer_5        7.402439
away_scorer_1       19.878049
away_scorer_2       17.134146
away_scorer_3       15.317073
away_scorer_4        7.951220
away_scorer_5        7.951220
home_rebounder_1     7.426829
home_rebounder_2     7.170732
home_rebounder_3     6.463415
home_rebounder_4     4.926829
home_rebounder_5     3.341463
away_rebounder_1     7.268293
away_rebounder_2     4.414634
away_rebounder_3     4.097561
away_rebounder_4     4.085366
away_rebounder_5     3.963415
Name: 0, dtype: float64

In [30]:
# = Datasets(clean_df.iloc[0])
test_dl = learner2.dls.test_dl(clean_df) # Create a test dataloader

In [50]:
#learner2.get_preds(dl=[clean_df.iloc[0]])
a = learner2.get_preds(dl = test_dl, reorder=False) # Make predictions on it

In [51]:
len(a[0])

6261

In [52]:
len(clean_df)

6261

In [53]:
len(a[1])

6261

In [54]:
a[0]

tensor([[0.3181, 0.6819],
        [0.4882, 0.5118],
        [0.3181, 0.6819],
        ...,
        [0.6065, 0.3935],
        [0.5504, 0.4496],
        [0.2722, 0.7278]])

In [55]:
clean_df

home_won  home_scorer_1  home_scorer_2  home_scorer_3  home_scorer_4  \
0            0      24.951220      19.012195      10.500000       8.548780   
1            1      19.878049      17.134146      15.317073       7.951220   
2            0      24.951220      19.012195      10.500000       8.548780   
3            1      24.951220      19.012195      10.500000       8.548780   
4            1      19.878049      17.134146      15.317073       7.951220   
...        ...            ...            ...            ...            ...   
6256         0      16.414634      15.500000      12.341463       7.158537   
6257         1      19.707317      12.292683      11.512195      11.463415   
6258         0      17.707317      12.780488       8.182927       4.707317   
6259         0      21.853659      17.817073      16.414634       9.426829   
6260         1      27.451220      12.670732      10.317073       3.743902   

      home_scorer_5  away_scorer_1  away_scorer_2  away_scorer_3  \
0          7.402439      19.878049      17.134146      15.317073   
1          7.951220      24.951220      19.012195      10.500000   
2          7.402439      19.878049      17.134146      15.317073   
3          7.402439      19.878049      17.134146      15.317073   
4          7.951220      24.951220      19.012195      10.500000   
...             ...            ...            ...            ...   
6256       6.780488      23.926829      21.121951      13.804878   
6257       9.219512      16.890244      16.487805      15.463415   
6258       1.597561      15.865854      14.121951      10.195122   
6259       4.682927      26.719512      15.158537      13.182927   
6260       2.902439      17.878049      13.560976      12.402439   

      away_scorer_4  ...  home_rebounder_1  home_rebounder_2  \
0          7.951220  ...          7.426829          7.170732   
1          8.548780  ...          7.268293          4.414634   
2          7.951220  ...          7.426829          7.170732   
3          7.951220  ...          7.426829          7.170732   
4          8.548780  ...          7.268293          4.414634   
...             ...  ...               ...               ...   
6256       7.853659  ...          6.317073          4.817073   
6257      14.268293  ...          7.329268          6.731707   
6258       9.475610  ...          5.707317          5.414634   
6259      12.512195  ...          6.524390          5.658537   
6260      11.304878  ...          8.646341          6.658537   

      home_rebounder_3  home_rebounder_4  home_rebounder_5  away_rebounder_1  \
0             6.463415          4.926829          3.341463          7.268293   
1             4.097561          4.085366          3.963415          7.426829   
2             6.463415          4.926829          3.341463          7.268293   
3             6.463415          4.926829          3.341463          7.268293   
4             4.097561          4.085366          3.963415          7.426829   
...                ...               ...               ...               ...   
6256          4.280488          4.060976          2.975610          8.634146   
6257          4.280488          4.195122          3.609756          9.792683   
6258          3.170732          2.853659          2.048780          6.597561   
6259          3.378049          3.182927          3.000000          9.780488   
6260          4.292683          3.000000          1.463415          6.475610   

      away_rebounder_2  away_rebounder_3  away_rebounder_4  away_rebounder_5  
0             4.414634          4.097561          4.085366          3.963415  
1             7.170732          6.463415          4.926829          3.341463  
2             4.414634          4.097561          4.085366          3.963415  
3             4.414634          4.097561          4.085366          3.963415  
4             7.170732          6.463415          4.926829          3.341463  
...                ...               ...        

In [56]:
a[0]

tensor([[0.3181, 0.6819],
        [0.4882, 0.5118],
        [0.3181, 0.6819],
        ...,
        [0.6065, 0.3935],
        [0.5504, 0.4496],
        [0.2722, 0.7278]])

In [57]:
a[1]

tensor([[0],
        [1],
        [0],
        ...,
        [0],
        [0],
        [1]], dtype=torch.int8)

In [62]:
learner2.predict(clean_df.iloc[2])

(   home_scorer_1  home_scorer_2  home_scorer_3  home_scorer_4  home_scorer_5  \
 0       1.341905       1.539844      -0.493097      -0.525795      -0.298516   
 
    away_scorer_1  away_scorer_2  away_scorer_3  away_scorer_4  away_scorer_5  \
 0       0.170147       0.909272       1.475447      -0.805403      -0.044956   
 
    ...  home_rebounder_2  home_rebounder_3  home_rebounder_4  \
 0  ...          1.449007           2.18121          1.559764   
 
    home_rebounder_5  away_rebounder_1  away_rebounder_2  away_rebounder_3  \
 0          0.414418          -0.25663         -0.779908          -0.19157   
 
    away_rebounder_4  away_rebounder_5  home_won  
 0          0.535016          1.261637       1.0  
 
 [1 rows x 21 columns],
 tensor(1),
 tensor([0.3181, 0.6819]))

In [65]:
np.random.random(2)

array([0.61501803, 0.6621681 ])